### PR TITLE
Revert "added file"

### PR DESCRIPTION
**Pull request by hyperplane-crew**
Reverts hyperplane-research/Hello-World#1

### CODE REVIEW

**Comment by hyperplane-crew** [comment]
test this please

**Comment by shreyu86** [comment]
test this please and ok to merge

**Comment by hyperplane-crew** [comment]
test this please

**Comment by hyperplane-crew** [comment]
test this please

**Comment by shreyu86** [comment]
test this please

**Comment by shreyu86** [comment]
test this please

**Pull request merged**
